TRAIN:
  ENABLE: True
  DATASET: EpicKitchensGRU
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: models/asf/weights/SLOWFAST_EPIC.pyth
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
  SUPERVISION_TYPE: "half"

DATA:
  INPUT_CHANNEL_NUM: [1, 1]
  ONLY_SYMBOLIC_STATE: False

AUDIO_DATA:
  CLIP_SECS: 1.999
  NUM_FRAMES: 400

  # The overlap is in seconds
  SPECTROGRAM_OVERLAP: 1.0

  # Maximum number of spectrograms per action segment to use.
  MAX_NB_SPECTROGRAMS: 20

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  FREQUENCY_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  FREQUENCY_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 64

SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.2, 0.02]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: [97, 300] # This will be updated by the state files into a 3-element list
  VOCAB_FILE: models/asf/config/vocab.txt
  PDDL_ATTRIBUTES: models/asf/config/attributes.csv
  ARCH: slowfast
  MODEL_NAME: AudioSlowFastGRU
  LOSS_FUNC: cross_entropy
  STATE_LOSS_FUNC: masked_loss
  DROPOUT_RATE: 0.5

  ONLY_ACTION_RECOGNITION: True

  # Adds CLIP
  CLIP_MODEL: ViT-B/32

TEST:
  ENABLE: False
  DATASET: EpicKitchens
  BATCH_SIZE: 128

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

EPICKITCHENS:
  TRAIN_PLUS_VAL: False
  AUDIO_DATA_FILE: /scratch/work/ptg/EPIC-KITCHENS/EPIC_audio.hdf5
  TRAIN_LIST: data/epic-kitchens-100-annotations/filtered_train.pkl
  TEST_LIST: data/epic-kitchens-100-annotations/filtered_val.pkl
  VAL_LIST: data/epic-kitchens-100-annotations/filtered_val.pkl

  # Vocab files
  VERBS_FILE: data/epic-kitchens-100-annotations/EPIC_100_verb_classes.csv
  NOUNS_FILE: data/epic-kitchens-100-annotations/EPIC_100_noun_classes.csv

  # PDDL
  PDDL_DOMAIN: pddl/domain.pddl
  PDDL_PROBLEM: pddl/problem.pddl

  # CLIP nouns embeddings
  NOUNS_EMBEDDINGS_FILE: data/epic-kitchens-100-annotations/nouns_embeddings.pkl

  # Augmentation
  AUGMENT:
    ENABLE: True
    FACTOR: 4.0

TENSORBOARD:
  ENABLE: True
  LOG_DIR: tensorboard

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 25
OUTPUT_DIR: .
WANDB:
  # ENABLE: True # If no GPU is enabled this will be set to False
  ENABLE: False # If no GPU is enabled this will be set to False
