TRAIN:
  ENABLE: True
  DATASET: EpicKitchensSlide
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: models/asf/weights/SLOWFAST_EPIC.pyth
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True

DATA:
  INPUT_CHANNEL_NUM: [1, 1]

AUDIO_DATA:
  CLIP_SECS: 1.999
  NUM_FRAMES: 400

  HOP_LENGTH: 2.5

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  FREQUENCY_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  FREQUENCY_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: slowfast
  MODEL_NAME: AudioSlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

  ONLY_ACTION_RECOGNITION: True

TEST:
  ENABLE: False
  DATASET: EpicKitchensSlide
  BATCH_SIZE: 128
  CHECKPOINT_FILE_PATH: models/asf/weights/SLOWFAST_EPIC.pyth
  NUM_ENSEMBLE_VIEWS: 1
  SLIDE:
    ENABLE: True
    WIN_SIZE: 2.0
    HOP_SIZE: 0.5
    LABEL_FRAME: 0.5
    INSIDE_ACTION_BOUNDS: False
    PER_ACTION_INSTANCE: False

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

EPICKITCHENS:
  SKIP_PREPARATION: True
  TRAIN_PLUS_VAL: False
  # SINGLE_BATCH: True

  AUDIO_DATA_FILE: /scratch/work/ptg/EPIC-KITCHENS/EPIC_audio.hdf5

  ORIGINAL_TRAIN_LIST: data/epic-kitchens-100-annotations/EPIC_100_train.pkl
  ORIGINAL_VAL_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  ORIGINAL_TEST_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  PROCESSED_TRAIN_LIST: data/epic-kitchens-100-annotations/EPIC_100_train.pkl
  PROCESSED_VAL_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  PROCESSED_TEST_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl

  VERBS_FILE: data/epic-kitchens-100-annotations/EPIC_100_verb_classes.csv
  NOUNS_FILE: data/epic-kitchens-100-annotations/EPIC_100_noun_classes.csv

  VIDEO_DURS: data/epic-kitchens-100-annotations/EPIC_100_video_info.csv

  AUGMENT:
    ENABLE: False
    BALANCE: False

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: runs/asf-original-slide

WANDB:
  ENABLE: True
